# Generated by Django 2.1.7 on 2025-08-01 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(default='Unknown Device', max_length=255)),
                ('os_info', models.CharField(default='Unknown OS', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('download_date', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZipFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='zips/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=20)),
                ('download_count', models.IntegerField(default=0)),
                ('is_download', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='downloadeddevice',
            name='zip_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update_ap.ZipFile'),
        ),
    ]
