# Generated by Django 2.1.7 on 2025-08-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_ap', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zipfile',
            unique_together={('name', 'version')},
        ),
    ]
